name: "NixOS Configuration Check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ["self-hosted", "linux", "arm64"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
            
      - name: Setup Home Manager
        run: |
          nix-channel --add https://github.com/nix-community/home-manager/archive/release-24.05.tar.gz home-manager
          nix-channel --update
          # 确保 home-manager channel 被正确安装
          sudo -i nix-channel --add https://github.com/nix-community/home-manager/archive/release-24.05.tar.gz home-manager
          sudo -i nix-channel --update
          
      - name: Validate Nix syntax
        run: |
          find . -name "*.nix" -type f -exec nix-instantiate --parse {} \;
          
      - name: Check NixOS configuration
        run: |
          # Enable Flakes feature
          export NIX_CONFIG="experimental-features = nix-command flakes"
          
          # Check flake.nix syntax
          nix flake check
          
          # Check all NixOS system configurations
          nix build .#nixosConfigurations.*.config.system.build.toplevel --dry-run
          
          # Check all Home Manager configurations
          nix build .#homeConfigurations.*.activationPackage --dry-run