name: "NixOS Configuration Check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
            
      - name: Validate Nix syntax
        run: |
          find . -name "*.nix" -type f -exec nix-instantiate --parse {} \;
          
      - name: Generate hardware configuration
        run: |
          # Install nixos-generate-config
          nix-env -iA nixpkgs.nixos-generate-config
          
          # Generate hardware configuration
          sudo nixos-generate-config --no-filesystems --show-hardware-config > hardware-configuration.nix
          
      - name: Check NixOS configuration
        run: |
          # Validate main configuration
          nix-instantiate --expr "import <nixpkgs/nixos> { configuration = ./configuration.nix; }" --dry-run
          
          # Build the system configuration
          nix-build '<nixpkgs/nixos>' -A system --dry-run -I nixos-config=./configuration.nix
          
          # Validate individual modules (excluding hardware-configuration.nix)
          for module in modules/*.nix; do
            echo "Checking $module..."
            nix-instantiate --expr "with import <nixpkgs/nixos> {}; (import $module)" --dry-run
          done