name: "NixOS Configuration Check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Check NixOS Configuration
      run: |
        # Check configuration.nix syntax
        nix-instantiate configuration.nix --dry-run
        
        # Try to build system configuration
        nixos-rebuild build --dry-run