name: "NixOS Configuration Check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
            
      - name: Check Nix files formatting
        run: |
          nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check ."
          
      - name: Validate Nix syntax
        run: |
          find . -name "*.nix" -type f -exec nix-instantiate --parse {} \;
          
      - name: Check NixOS configuration
        run: |
          # Validate main configuration
          nix-instantiate --expr "import <nixpkgs/nixos> { configuration = ./configuration.nix; }" --dry-run
          
          # Build the system configuration
          nix-build '<nixpkgs/nixos>' -A system --dry-run -I nixos-config=./configuration.nix
          
          # Validate all imported modules
          for module in modules/*.nix; do
            echo "Checking $module..."
            nix-instantiate --expr "with import <nixpkgs/nixos> {}; (import $module)" --dry-run
          done